INSERT INTO categories (category_id, category_name, information) VALUES (1, 'Computer Accessories', 'Enhance computer functionality with peripherals.');
INSERT INTO categories (category_id, category_name, information) VALUES (2, 'Audio Equipment', 'Speakers and headphones for great sound.');
INSERT INTO categories (category_id, category_name, information) VALUES (3, 'Office Supplies', 'Stands, lamps, and organizers for office.');
INSERT INTO categories (category_id, category_name, information) VALUES (4, 'Networking', 'Routers and hubs for network management.');
INSERT INTO categories (category_id, category_name, information) VALUES (5, 'Gaming Gear', 'Keyboards, consoles, VR headsets.');
INSERT INTO categories (category_id, category_name, information) VALUES (6, 'Headphones & Earbuds', 'Personal audio: music, podcasts.');
INSERT INTO categories (category_id, category_name, information) VALUES (7, 'Mobile Accessories', 'Cases, chargers, gimbals for mobiles.');
INSERT INTO categories (category_id, category_name, information) VALUES (8, 'Wearable Technology', 'Smart watches, fitness trackers.');
INSERT INTO categories (category_id, category_name, information) VALUES (9, 'Cameras & Photography', 'Capture photos, videos with cameras.');
INSERT INTO categories (category_id, category_name, information) VALUES (10, 'Lighting', 'Lights for home and office use.');
INSERT INTO categories (category_id, category_name, information) VALUES (11, 'Data Storage', 'Store and manage data: hard drives.');
INSERT INTO categories (category_id, category_name, information) VALUES (12, 'Health & Fitness', 'Fitness trackers, smart scales.');
INSERT INTO categories (category_id, category_name, information) VALUES (13, 'Smart Home Devices', 'Thermostats, security cameras.');
INSERT INTO categories (category_id, category_name, information) VALUES (14, 'Small Kitchen Appliances', 'Blenders, coffee makers.');
INSERT INTO categories (category_id, category_name, information) VALUES (15, 'Home Cleaning', 'Robot vacuums, pressure washers.');
INSERT INTO categories (category_id, category_name, information) VALUES (16, 'Personal Care', 'Toothbrushes, shavers for grooming.');
INSERT INTO categories (category_id, category_name, information) VALUES (17, 'Medical Devices', 'Blood pressure devices for home.');
INSERT INTO categories (category_id, category_name, information) VALUES (18, 'Exercise Equipment', 'Yoga mats, treadmills for fitness.');
INSERT INTO categories (category_id, category_name, information) VALUES (19, 'Television & Home Theater', 'Smart TVs, projectors for entertainment.');
INSERT INTO categories (category_id, category_name, information) VALUES (20, 'Streaming & Media', 'Media streaming with sticks.');
INSERT INTO categories (category_id, category_name, information) VALUES (21, 'Outdoor & Garden', 'Garden tools, patio furniture.');
INSERT INTO categories (category_id, category_name, information) VALUES (22, 'Tools & Hardware', 'Drills, saws, toolkits for home.');
INSERT INTO categories (category_id, category_name, information) VALUES (23, 'Automotive Accessories', 'Car chargers, GPS, dash cams.');
INSERT INTO categories (category_id, category_name, information) VALUES (24, 'Travel Accessories', 'Travel pillows, suitcases, bags.');
INSERT INTO categories (category_id, category_name, information) VALUES (25, 'Fashion Accessories', 'Sunglasses, wallets for fashion.');
INSERT INTO categories (category_id, category_name, information) VALUES (26, 'Luggage & Bags', 'Camera bags, handbags, luggage.');
INSERT INTO categories (category_id, category_name, information) VALUES (27, 'Camera Accessories', 'Tripods, memory cards for photography.');
INSERT INTO categories (category_id, category_name, information) VALUES (28, 'Virtual Reality', 'VR headsets for virtual experiences.');
INSERT INTO categories (category_id, category_name, information) VALUES (29, 'Drones', 'Drones for photography, entertainment.');
INSERT INTO categories (category_id, category_name, information) VALUES (30, '3D Printing', '3D printers for creating objects.');
COMMIT;
